### ISSUE TITLE
Daemon will start synchronisation from block undefined

### ISSUE THREAD

**Issue by noisy** [wise-team/steem-wise-cli#27]
#### The problem: 

When using `wise init`, when `-b` is not provided, logs displays `undefined` in

#### I did:

`wise init`
I typed _noisy3_ as a username
I type _no_ to question about posting key

#### I expected to see:

> Daemon will start synchronisation from block HEAD

#### Instead, I saw:

> Daemon will start synchronisation from block undefined

-----------

Version of steem-wise-core: 3.0.6-rc1
Version of nodejs: 10.0.5

Links to gist with output / logs (or at least a picture):

![selection_999 651](https://user-images.githubusercontent.com/201263/49726235-cfa2fc00-fc6d-11e8-8c69-3b4f1d670b9c.png)

**Comment by Jblew** [comment]
Done.
